// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlMvY_U4S9BhROZ1q5WchAdXpTowz9wpw',
    appId: '1:631138453825:web:22fb0dc9a21703ce2f39c0',
    messagingSenderId: '631138453825',
    projectId: 'fluttertest-de8bc',
    authDomain: 'fluttertest-de8bc.firebaseapp.com',
    storageBucket: 'fluttertest-de8bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC73Y8EDGEl8xHJ5Xe4EI07DbqebWt-Xc',
    appId: '1:631138453825:android:d7487fc5a080503f2f39c0',
    messagingSenderId: '631138453825',
    projectId: 'fluttertest-de8bc',
    storageBucket: 'fluttertest-de8bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmeh39-vLljrgxdSYKDhOtp7CF2tzhmg',
    appId: '1:631138453825:ios:ef537c928c7055432f39c0',
    messagingSenderId: '631138453825',
    projectId: 'fluttertest-de8bc',
    storageBucket: 'fluttertest-de8bc.appspot.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOmeh39-vLljrgxdSYKDhOtp7CF2tzhmg',
    appId: '1:631138453825:ios:ef537c928c7055432f39c0',
    messagingSenderId: '631138453825',
    projectId: 'fluttertest-de8bc',
    storageBucket: 'fluttertest-de8bc.appspot.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlMvY_U4S9BhROZ1q5WchAdXpTowz9wpw',
    appId: '1:631138453825:web:07d91eb34aed85ee2f39c0',
    messagingSenderId: '631138453825',
    projectId: 'fluttertest-de8bc',
    authDomain: 'fluttertest-de8bc.firebaseapp.com',
    storageBucket: 'fluttertest-de8bc.appspot.com',
  );
}
